<?php

use Illuminate\Database\Seeder;
use App\Model\Product;


class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $product_name = [
          'Mahoni', 'Mahoni B', 'Agathis', 'Sungkai NS', 'Sungkai LS', 'Sungkai HS', 'Sungkai MS'
        ];

        Product::create(['company_id' => 4,'concession_id' => 1,'product_name' => 'Coal','typical_quality' => 'GAR4200','tm_min' => '35','tm_max' => null,'im_min' =>'18','im_max' =>null,'ash_min' =>'5','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '42','vm_max' => null,'ts_min' => '0.8','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '4200','gcv_adb_max' => null,'hgi_min' => '40','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'na2o_min'=> null,'na2o_max'=>null,'status' => 'a']);
        Product::create(['company_id' => 5,'concession_id' => 2,'product_name' => 'Mahoni','typical_quality' => 'GAR5500','tm_min' => '20','tm_max' => '14','im_min' =>'14','im_max' =>'0.9','ash_min' =>'5','ash_max' => '55','fc_min' => null,'fc_max' => null,'vm_min' => null,'vm_max' => null,'ts_min' => '0.9','ts_max' => '5','ncv_min' => '20','ncv_max' => '90','gcv_arb_min' => '5500','gcv_arb_max' => '5900','gcv_adb_min' => '5500','gcv_adb_max' => '5900','hgi_min' => '40','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> '5300','fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'na2o_min'=> null,'na2o_max'=>null,'status' => 'a']);
        Product::create(['company_id' => 5,'concession_id' => 3,'product_name' => 'Mahoni B','typical_quality' => 'GAR5800','tm_min' => '22.5','tm_max' => '16','im_min' =>'16','im_max' =>'0.9','ash_min' =>'5','ash_max' => '55','fc_min' => null,'fc_max' => null,'vm_min' => null,'vm_max' => null,'ts_min' => '0.9','ts_max' => '5','ncv_min' => '22.5','ncv_max' => '5900','gcv_arb_min' => '5300','gcv_arb_max' => '5750','gcv_adb_min' => '5300','gcv_adb_max' => '5750','hgi_min' => '40','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> '50','fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'na2o_min'=> null,'na2o_max'=>null,'status' => 'a']);
        Product::create(['company_id' => 5,'concession_id' => 3,'product_name' => 'Sungkai','typical_quality' => 'NAR3200','tm_min' => '25','tm_max' => '28','im_min' =>'28','im_max' =>'1','ash_min' =>'5','ash_max' => '55','fc_min' => null,'fc_max' => null,'vm_min' => null,'vm_max' => null,'ts_min' => '1','ts_max' => '5','ncv_min' => '2500','ncv_max' => '90','gcv_arb_min' => '5000','gcv_arb_max' => '5500','gcv_adb_min' => '5000','gcv_adb_max' => '5500','hgi_min' => '40','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> '4600','fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'na2o_min'=> null,'na2o_max'=>null,'status' => 'a']);
        Product::create(['company_id' => 6,'concession_id' => 4,'product_name' => 'Coal','typical_quality' => 'GAR5500','tm_min' => '37','tm_max' => '37','im_min' =>'15','im_max' =>'15','ash_min' =>'6','ash_max' => '6','fc_min' => null,'fc_max' => null,'vm_min' => '42','vm_max' => null,'ts_min' => '0.3','ts_max' => '0.3','ncv_min' => '5500','ncv_max' => '3800','gcv_arb_min' => null,'gcv_arb_max' => '4200','gcv_adb_min' => '4200','gcv_adb_max' => '5500','hgi_min' => '55','hgi_max' => null,'size_min' => '90','size_max' => null,'fe2o3_min'=> '20','fe2o3_max'=> null,'aft_min'=> '1150','aft_max'=>null,'na2o_min'=> null,'na2o_max'=>null,'status' => 'a']);
        Product::create(['company_id' => 7,'concession_id' => 5,'product_name' => 'Coal','typical_quality' => 'GAR5500','tm_min' => '20','tm_max' => null,'im_min' =>'14','im_max' =>null,'ash_min' =>'5','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '40','vm_max' => null,'ts_min' => '0.3','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '5500','gcv_adb_max' => null,'hgi_min' => '45','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'na2o_min'=> null,'na2o_max'=>null,'status' => 'a']);




        // Product::create(['company_id' => 3,'concession_id' => 3,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '14','tm_max' => null,'im_min' =>'6','im_max' =>null,'ash_min' =>'14','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '40','vm_max' => null,'ts_min' => '0.6','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '5800','gcv_adb_max' => null,'hgi_min' => '40','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 4,'concession_id' => 4,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '38','tm_max' => null,'im_min' =>'13','im_max' =>null,'ash_min' =>'7','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '45','vm_max' => null,'ts_min' => '0.5','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '3700','gcv_adb_max' => '5300','hgi_min' => '48','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 5,'concession_id' => 5,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '19','tm_max' => null,'im_min' =>'14','im_max' =>null,'ash_min' =>'7','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '40','vm_max' => null,'ts_min' => '1','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '5200','gcv_adb_max' => null,'hgi_min' => '45','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        
        
        // Product::create(['company_id' => 8,'concession_id' => 8,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '20','tm_max' => null,'im_min' =>null,'im_max' =>null,'ash_min' =>'4','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '0','vm_max' => null,'ts_min' => '0.5','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '5600','gcv_adb_max' => null,'hgi_min' => null,'hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 9,'concession_id' => 9,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '17','tm_max' => null,'im_min' =>'10','im_max' =>null,'ash_min' =>'10','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '39','vm_max' => null,'ts_min' => '1.5','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '5700','gcv_adb_max' => null,'hgi_min' => '45','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 10,'concession_id' => 10,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '36','tm_max' => null,'im_min' =>'14','im_max' =>null,'ash_min' =>'6','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '42','vm_max' => null,'ts_min' => '0.4','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => '4200','gcv_adb_min' => '4200','gcv_adb_max' => null,'hgi_min' => '60','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 11,'concession_id' => 11,'product_name' => 'Roto','typical_quality' => 'Coal','tm_min' => '27','tm_max' => '27','im_min' =>'15','im_max' =>'15','ash_min' =>'2.5','ash_max' => '2.5','fc_min' => null,'fc_max' => null,'vm_min' => '40','vm_max' => null,'ts_min' => '0.1','ts_max' => '0.1','ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => '4800','gcv_adb_min' => '4800','gcv_adb_max' => null,'hgi_min' => '50','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 12,'concession_id' => 12,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '29','tm_max' => null,'im_min' =>'14.5','im_max' =>null,'ash_min' =>'5','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '42','vm_max' => null,'ts_min' => '0.5','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '4900','gcv_adb_max' => null,'hgi_min' => '45','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 13,'concession_id' => 13,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '39','tm_max' => null,'im_min' =>'15','im_max' =>null,'ash_min' =>'4','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '42','vm_max' => null,'ts_min' => '0.2','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '3800','gcv_adb_max' => null,'hgi_min' => '60','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 14,'concession_id' => 14,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '13','tm_max' => null,'im_min' =>'2','im_max' =>null,'ash_min' =>'16','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '25','vm_max' => null,'ts_min' => '0.8','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '6800','gcv_adb_max' => null,'hgi_min' => '90','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 15,'concession_id' => 15,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '30','tm_max' => null,'im_min' =>'13','im_max' =>null,'ash_min' =>'8','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '42','vm_max' => null,'ts_min' => '0.8','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '4400','gcv_adb_max' => null,'hgi_min' => '50','hgi_max' => null,'size_min' => '0','size_max' => null,'fe2o3_min'=> '0','fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 16,'concession_id' => 16,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '28','tm_max' => null,'im_min' =>'13','im_max' =>null,'ash_min' =>'8','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '42','vm_max' => null,'ts_min' => '0.8','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '4500','gcv_adb_max' => null,'hgi_min' => '50','hgi_max' => null,'size_min' => '0','size_max' => null,'fe2o3_min'=> '0','fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 17,'concession_id' => 17,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '19','tm_max' => null,'im_min' =>'10','im_max' =>null,'ash_min' =>'8','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '38','vm_max' => null,'ts_min' => '0.4','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '5000','gcv_adb_max' => '6000','hgi_min' => '45','hgi_max' => null,'size_min' => '90','size_max' => null,'fe2o3_min'=> '0','fe2o3_max'=> null,'aft_min'=> '0','aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 18,'concession_id' => 18,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '28','tm_max' => null,'im_min' =>'12','im_max' =>null,'ash_min' =>'7.5','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '42','vm_max' => null,'ts_min' => '1.4','ts_max' => null,'ncv_min' => null,'ncv_max' => '4650','gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '5000','gcv_adb_max' => '5700','hgi_min' => '55','hgi_max' => null,'size_min' => '90','size_max' => null,'fe2o3_min'=> '7','fe2o3_max'=> null,'aft_min'=> '1400','aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 19,'concession_id' => 19,'product_name' => 'Agathis','typical_quality' => 'Coal','tm_min' => '25','tm_max' => '17','im_min' =>'17','im_max' =>'0.9','ash_min' =>'5','ash_max' => '55','fc_min' => null,'fc_max' => null,'vm_min' => null,'vm_max' => null,'ts_min' => '0.9','ts_max' => '5','ncv_min' => '2500','ncv_max' => '90','gcv_arb_min' => '5100','gcv_arb_max' => '5650','gcv_adb_min' => '5100','gcv_adb_max' => '5650','hgi_min' => '40','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> '4800','fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        
        // Product::create(['company_id' => 21,'concession_id' => 21,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '36','tm_max' => null,'im_min' =>'15','im_max' =>null,'ash_min' =>'6','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '42','vm_max' => null,'ts_min' => '0.4','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '5500','gcv_adb_max' => null,'hgi_min' => '55','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 22,'concession_id' => 22,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '18','tm_max' => null,'im_min' =>'6','im_max' =>null,'ash_min' =>'12','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '38','vm_max' => null,'ts_min' => '2.5','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '5500','gcv_adb_max' => null,'hgi_min' => '50','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 23,'concession_id' => 23,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '23','tm_max' => null,'im_min' =>'13','im_max' =>null,'ash_min' =>'8','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '40','vm_max' => null,'ts_min' => '0.6','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '5600','gcv_adb_max' => null,'hgi_min' => '50','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 24,'concession_id' => 24,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '37','tm_max' => null,'im_min' =>'15','im_max' =>null,'ash_min' =>'6','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '40','vm_max' => null,'ts_min' => '0.6','ts_max' => null,'ncv_min' => null,'ncv_max' => '3','gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '4000','gcv_adb_max' => '5000','hgi_min' => '45','hgi_max' => null,'size_min' => '0','size_max' => null,'fe2o3_min'=> '0','fe2o3_max'=> null,'aft_min'=> '0','aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 25,'concession_id' => 25,'product_name' => 'SM','typical_quality' => 'Coal','tm_min' => '35','tm_max' => '35','im_min' =>'15','im_max' =>'15','ash_min' =>'3.5','ash_max' => '3.5','fc_min' => null,'fc_max' => null,'vm_min' => '40','vm_max' => null,'ts_min' => '0.1','ts_max' => '0.1','ncv_min' => null,'ncv_max' => '3800','gcv_arb_min' => null,'gcv_arb_max' => '4200','gcv_adb_min' => '4200','gcv_adb_max' => null,'hgi_min' => '50','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 26,'concession_id' => 26,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '20','tm_max' => null,'im_min' =>'15','im_max' =>null,'ash_min' =>'6','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '40','vm_max' => null,'ts_min' => '0.6','ts_max' => null,'ncv_min' => null,'ncv_max' => '4','gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '4000','gcv_adb_max' => '4000','hgi_min' => '45','hgi_max' => null,'size_min' => '0','size_max' => null,'fe2o3_min'=> '0','fe2o3_max'=> null,'aft_min'=> '0','aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 27,'concession_id' => 27,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '40','tm_max' => null,'im_min' =>'13','im_max' =>null,'ash_min' =>'5','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '45','vm_max' => null,'ts_min' => '0.5','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '3600','gcv_adb_max' => '5400','hgi_min' => '40','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> null,'fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 28,'concession_id' => 28,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '28','tm_max' => null,'im_min' =>'13','im_max' =>null,'ash_min' =>'8','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '42','vm_max' => null,'ts_min' => '0.8','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '4600','gcv_adb_max' => null,'hgi_min' => '50','hgi_max' => null,'size_min' => '0','size_max' => null,'fe2o3_min'=> '0','fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 29,'concession_id' => 29,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '12','tm_max' => null,'im_min' =>'12','im_max' =>null,'ash_min' =>'10','ash_max' => null,'fc_min' => null,'fc_max' => null,'vm_min' => '42','vm_max' => null,'ts_min' => '0.8','ts_max' => null,'ncv_min' => null,'ncv_max' => null,'gcv_arb_min' => null,'gcv_arb_max' => null,'gcv_adb_min' => '6300','gcv_adb_max' => null,'hgi_min' => '48','hgi_max' => null,'size_min' => '0','size_max' => null,'fe2o3_min'=> '0','fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 30,'concession_id' => 30,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '24','tm_max' => '13','im_min' =>'13','im_max' =>'1.5','ash_min' =>'15','ash_max' => '60','fc_min' => null,'fc_max' => null,'vm_min' => '0','vm_max' => null,'ts_min' => '1.5','ts_max' => '15','ncv_min' => '2400','ncv_max' => '90','gcv_arb_min' => '4800','gcv_arb_max' => '5700','gcv_adb_min' => '4800','gcv_adb_max' => '5700','hgi_min' => '40','hgi_max' => null,'size_min' => null,'size_max' => null,'fe2o3_min'=> '4400','fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        
        // Product::create(['company_id' => 32,'concession_id' => 32,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '24','tm_max' => '24','im_min' =>'13','im_max' =>'13','ash_min' =>'15','ash_max' => '15','fc_min' => null,'fc_max' => null,'vm_min' => '40','vm_max' => null,'ts_min' => '1.5','ts_max' => '1.5','ncv_min' => '5700','ncv_max' => '4400','gcv_arb_min' => null,'gcv_arb_max' => '4800','gcv_adb_min' => '4800','gcv_adb_max' => '5700','hgi_min' => '60','hgi_max' => null,'size_min' => '90','size_max' => null,'fe2o3_min'=> '0','fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);
        // Product::create(['company_id' => 33,'concession_id' => 33,'product_name' => 'Coal','typical_quality' => 'Coal','tm_min' => '24','tm_max' => '24','im_min' =>'13','im_max' =>'13','ash_min' =>'15','ash_max' => '15','fc_min' => null,'fc_max' => null,'vm_min' => '40','vm_max' => null,'ts_min' => '1.5','ts_max' => '1.5','ncv_min' => '5700','ncv_max' => '4400','gcv_arb_min' => null,'gcv_arb_max' => '4800','gcv_adb_min' => '4800','gcv_adb_max' => '5700','hgi_min' => '60','hgi_max' => null,'size_min' => '90','size_max' => null,'fe2o3_min'=> '0','fe2o3_max'=> null,'aft_min'=> null,'aft_max'=>null,'status' => 'a']);

        /*foreach(range(0,6) as $index)
        {
        	$faker = Faker\Factory::create(); 

          Product::create([
            'concession_id' => $faker->numberBetween($min = 0, $max = 2),
			'product_name' => $product_name[$index],
            'tm_min' => $faker->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 0.5),
            'tm_max' => $faker->randomFloat($nbMaxDecimals = 2, $min = 0.5, $max = 1.5),
            'im_min' => $faker->randomFloat($nbMaxDecimals = 2, $min = 0, $max = 0.3),
            'im_max' => $faker->randomFloat($nbMaxDecimals = 2, $min = 0.3, $max = 0.5),
            'ash_min' => $faker->randomFloat($nbMaxDecimals = 2, $min = 2, $max = 5),
            'ash_max' => $faker->randomFloat($nbMaxDecimals = 2, $min = 5, $max = 7),
            'fc_min' => $faker->randomFloat($nbMaxDecimals = 2, $min = 2, $max = 5),
            'fc_max' => $faker->randomFloat($nbMaxDecimals = 2, $min = 5, $max = 7),
            'vm_min' => $faker->randomFloat($nbMaxDecimals = 2, $min = 1, $max = 3),
            'vm_max' => $faker->randomFloat($nbMaxDecimals = 2, $min = 3, $max = 5),
            'ts_min' => $faker->randomFloat($nbMaxDecimals = 2, $min = 10, $max = 15),
            'ts_max' => $faker->randomFloat($nbMaxDecimals = 2, $min = 15, $max = 20),
            'ncv_min' => $faker->numberBetween($min = 50, $max = 55)*100,
            'ncv_max' => $faker->numberBetween($min = 55, $max = 60)*100,
            'gcv_arb_min' => $faker->numberBetween($min = 50, $max = 55)*100,
            'gcv_arb_max' => $faker->numberBetween($min = 55, $max = 60)*100,
            'gcv_adb_min' => $faker->numberBetween($min = 50, $max = 55)*100,
            'gcv_adb_max' => $faker->numberBetween($min = 55, $max = 60)*100,
            'hgi_min' => $faker->numberBetween($min = 40, $max = 55),
            'hgi_max' => $faker->numberBetween($min = 55, $max = 70),
            'size_min' => $faker->numberBetween($min = 40, $max = 45),
            'size_max' => $faker->numberBetween($min = 45, $max = 50),
            'fe2o3_min'=> $faker->numberBetween($min = 45, $max = 50),
            'fe2o3_max'=> $faker->numberBetween($min = 45, $max = 50),  
            'cvnar_min'=> $faker->numberBetween($min = 45, $max = 50), 
            'cvnar_max'=> $faker->numberBetween($min = 45, $max = 50),
            'aft_min'=> $faker->numberBetween($min = 45, $max = 50), 
            'aft_max'=> $faker->numberBetween($min = 45, $max = 50),
            'status' => 'a'
          ]);
        }*/
    }
}
