before_script:
  - git submodule update --init
  - php -v
  - composer --version
  - git --version
  - ls -lah
  - composer self-update
  - composer install --no-interaction
  - php artisan env
  - php artisan migrate --seed

stages:
  - build

build:
  script:
  - gulp