image: kahunacoder/docker-laravel-gulp

development:
  before_script:
    - npm install
  script:
    - gulp lint
  only:
    - development

release:
  before_script:
    - npm install -g bower
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - npm install
    - bower install --allow-root
    - composer install --no-interaction
    - php artisan migrate --seed
  script:
    - gulp build
  only:
    - release

master:
  before_script:
    - npm install -g bower
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - npm install
    - bower install --allow-root
    - composer install --no-interaction
  script:
    - gulp build
  only:
    - master