#image: karbon001/gitlab-ci-laravel-php
image: kahunacoder/docker-laravel-gulp
  
before_script:
  # - php -v
  # - composer --version
  # - ls -lah
  # - composer install --no-interaction
  # - php artisan env
  # - npm install
  # - bower install
  # - php artisan migrate --seed
  - npm install gulp gulp-load-plugins run-sequence gulp-angular-templatecache gulp-concat gulp-sourcemaps gulp-concat-sourcemap gulp-eslint gulp-uglify gulp-sass gulp-ng-annotate gulp-notify gulp-if run-sequence laravel-elixir

build:
  script:
    - gulp build