#image: karbon001/gitlab-ci-laravel-php
image: kahunacoder/docker-laravel-gulp
  
before_script:
  # - php -v
  # - composer --version
  # - ls -lah
  # - composer install --no-interaction
  # - php artisan env
  # - npm install
  # - npm install -g bower
  # - bower install
  # - php artisan migrate --seed
  - npm install

build:
  script:
    - gulp build