image: php:7.0
  
before_script:
  - php -v
  - composer --version
  - git --version
  - ls -lah
  - composer self-update
  - composer config --global github-oauth.github.com $GITHUB_TOKEN
  - composer install --no-interaction
  - php artisan env
  - npm install
  - bower install
#  - php artisan migrate --seed

build:
  script:
    - gulp