image: karbon001/gitlab-ci-laravel-php
  
before_script:
  - apt-get -y install npm 
  - npm install -g bower gulp
  - php -v
  - composer --version
  - ls -lah
  - composer install --no-interaction
  - php artisan env
  - npm install
  - bower install
#  - php artisan migrate --seed

build:
  script:
    - gulp build