<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateIndexTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('index', function (Blueprint $table) {
            $table->increments('id');
            $table->string('index_provider');
            $table->string('index_name');
            $table->string('quality')->nullable();
            $table->char('frequency', 1);
            $table->char('status', 1);
            $table->timestamps();
        });
        
        Schema::create('index_price', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('index_id')->unsigned();
            $table->date('date');
            $table->integer('day_of_year');
            $table->integer('day_of_month');
            $table->integer('day_of_week');
            $table->integer('week');
            $table->integer('month');
            $table->integer('year');
            $table->decimal('price',7,2);
            $table->boolean('is_autogenerated')->default(true);
            $table->char('status', 1);
            $table->timestamps();

            $table->foreign('index_id')->references('id')->on('index')->onDelete('restrict');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('index_price');
        Schema::dropIfExists('index');
    }
}
