<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateIndexPriceTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('index_price', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('index_id');
            $table->date('date');
            $table->integer('day_of_year');
            $table->integer('day_of_month');
            $table->integer('day_of_week');
            $table->integer('week');
            $table->integer('month');
            $table->integer('year');
            $table->decimal('price',7,2);
            $table->boolean('is_autogenerated')->default(true);
            
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
